// ======================================================================== //
//                                                                          //
// piInterrupts.H                                                           //
//                                                                          //
// ======================================================================== //
// Interrupt handler class for the Raspberry Pi                             //
// ======================================================================== //

#ifndef __WIRING_PI_piInterrupts_H
#define __WIRING_PI_piInterrupts_H

#include "wiringPi.H"

namespace WiringPi
{
    class piInterrupts
    {
    public:
        [[nodiscard]] inline piInterrupts() {};

    private:
    };
}

#endif
