#ifndef __WIRING_PI_INCLUDES_H
#define __WIRING_PI_INCLUDES_H

// Header includes
#include <iostream>
#include <vector>
#include <array>
#include <stddef.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdlib.h>
#include <ctype.h>
#include <poll.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <time.h>
#include <fcntl.h>
#include <pthread.h>
#include <sys/time.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/ioctl.h>
#include <asm/ioctl.h>
#include <string>
#include <memory>
#include <utility>
#include <algorithm>
#include <cassert>
#include <string_view>

#endif