// ======================================================================== //
//                                                                          //
// wiringPiIncludes.H                                                       //
//                                                                          //
// ======================================================================== //
// Header includes necessary for the library                                //
// ======================================================================== //

#ifndef __WIRING_PI_wiringPiIncludes_H
#define __WIRING_PI_wiringPiIncludes_H

// Header includes
#include <algorithm>
#include <array>
#include <asm/ioctl.h>
#include <atomic>
#include <cassert>
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <iostream>
#include <memory>
#include <poll.h>
#include <pthread.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <string.h>
#include <string_view>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
#include <utility>
#include <vector>

#endif
